GCW-3462 submit phone number to send pin endpoint
crossroads/app.goodchat.hk pull request #21
Opened 2021-01-20 02:43 UTC by BboyStatix

## Ticket Link
https://jira.crossroads.org.hk/browse/GCW-3462
## What does this PR do?
Creates the UI that allows user to input their phone number and submit the information to `auth/send_pin`.

2021-01-20 03:02 UTC, patrixr requested changes

2021-01-20 03:14 UTC, BboyStatix commented on src/pages/Login/Login.tsx
> +    AuthenticationService.sendPin({ mobile });
Will do so. In another PR

2021-01-20 03:19 UTC, BboyStatix commented on src/pages/Login/Login.test.tsx
> +test("renders an ion-item", () => {
### Without IonItem
<img width="471" alt="without" src="https://user-images.githubusercontent.com/19769879/105122386-1338e700-5b11-11eb-8196-ddebb1532516.png">
### With IonItem
<img width="454" alt="Screenshot 2021-01-20 at 11 16 07 AM" src="https://user-images.githubusercontent.com/19769879/105122393-16cc6e00-5b11-11eb-80cd-fcaa1bf7bf53.png">

Therefore, it seems to me that `IonItem` has importance in the sense that it is what results in the UI that we want.

2021-01-20 03:25 UTC, BboyStatix commented on src/pages/Login/Login.tsx
> +          Get 4-digit SMS code
Thanks for the heads up. I'll create a ticket for it.

2021-01-20 03:29 UTC, BboyStatix commented on src/pages/Login/Login.tsx
> +          Get 4-digit SMS code
Ticket created https://jira.crossroads.org.hk/browse/GCW-3480

2021-01-20 05:04 UTC, patrixr commented on src/pages/Login/Login.tsx
> +    AuthenticationService.sendPin({ mobile });
I would consider this a "critical" issue, so definitely to be fixed before merging.
However you can do a rough try/catch+error now and improve in another PR using hooks later

The general premise when reviewing/merging code, is that we don't want to introduce breaking changes, bugs or broken features into the main branch.

2021-01-20 05:06 UTC, patrixr commented on src/pages/Login/Login.test.tsx
> +test("renders an ion-item", () => {
That's not the point. The point is that the spec doesn't make sense. The fact that you use an `IonItem` is part of the implementation, it's not part of the business requirements. So you shouldn't test that

2021-01-20 05:06 UTC, patrixr commented on src/pages/Login/Login.tsx
> +          Get 4-digit SMS code
Cool 👍

2021-01-22 07:30 UTC, patrixr commented on src/pages/Login/Login.test.tsx
> +});
you can remove this

2021-01-22 07:34 UTC, patrixr commented on src/pages/Login/Login.test.tsx
> +  it("should log the error to the console", async () => {
`console.log` isn't really an error management, we probably want an error shown to the user

2021-01-22 07:37 UTC, patrixr commented on src/pages/Login/test_utils.ts
> +}
This makes the assumption that the container has `ion-item > ion-input` inside it, so maybe rename the method `fillIonInput` to be clearer, and you can probably do `querySelector('ion-input')` that way `ion-item` won't be required

2021-01-22 07:47 UTC, patrixr requested changes
Looks good overall, couple comments

2021-01-22 08:46 UTC, merged